AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  processCOVIDdataSNS:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.main_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 5
      Role: 'arn:aws:iam::########:role/lambda-vpc-role'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0/5 * * * ? *)
      VpcConfig:
        SecurityGroupIds:
          - sg---------
        SubnetIds:
          - subnet--------
          - subnet--------
      Layers:
        - 'arn:aws:lambda:us-east-1:#######:layer:pymysql:1'
        - >-
          arn:aws:lambda:us-east-1:######:layer:AWSLambda-Python38-SciPy1x:29
        - 'arn:aws:lambda:us-east-1:#######:layer:Klayers-python38-pandas:18'
